#!/usr/bin/env python3
"""Phase 9: build content/references.bib from provenance/crossref_metadata.json.
Deterministic. One BibTeX entry per citation key (citation_key_map.json).
Author given-names beyond the first author are not stored in crossref_metadata
(first-author given + all co-author families only); co-authors render family-only.
Phase 9 may enrich with full author lists via a direct CrossRef re-fetch if 9V requires it."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

km = json.load(open("provenance/citation_key_map.json", encoding="utf-8"))       # doi -> key
meta = json.load(open("provenance/crossref_metadata.json", encoding="utf-8"))     # list of records
by_doi = {(r.get("doi") or "").lower(): r for r in meta}

TYPE_MAP = {
    "journal-article": "article",
    "book-chapter": "incollection",
    "posted-content": "misc",
    "book": "book",
    "proceedings-article": "inproceedings",
    "report": "techreport",
    "dataset": "misc",
}

def esc(s):
    """Escape LaTeX/BibTeX special characters; leave unicode for latexcodec."""
    if s is None:
        return ""
    s = str(s)
    s = s.replace("\\", r"\textbackslash{}")
    for a, b in [("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"),
                 ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    return s

def author_field(r):
    fam = (r.get("family") or "").strip()
    given = (r.get("given") or "").strip()
    all_fam = [f for f in (r.get("all_families") or []) if (f or "").strip()]
    if not all_fam and fam:
        all_fam = [fam]
    names = []
    for i, f in enumerate(all_fam):
        f = f.strip()
        is_org = (" " in f) and (i == 0 and not given)   # corporate/consortium author
        if is_org:
            names.append("{" + esc(f) + "}")
        elif i == 0 and given:
            names.append(esc(f) + ", " + esc(given))
        else:
            names.append(esc(f))
    return " and ".join(names) if names else "{Anonymous}"

def entry(key, r):
    etype = TYPE_MAP.get(r.get("type"), "misc")
    fields = []
    fields.append(("author", author_field(r)))
    title = (r.get("title") or "").strip()
    fields.append(("title", "{" + esc(title) + "}"))    # double-brace: protect case
    year = r.get("year")
    if year:
        fields.append(("year", str(year)))
    container = (r.get("container") or "").strip()
    if container:
        cf = "journal" if etype == "article" else ("booktitle" if etype in ("incollection", "inproceedings") else "howpublished")
        fields.append((cf, esc(container)))
    doi = (r.get("doi") or "").strip()
    if doi:
        fields.append(("doi", esc(doi)))
        fields.append(("url", "https://doi.org/" + doi))
    body = ",\n".join("  %s = {%s}" % (k, v) for k, v in fields)
    return "@%s{%s,\n%s\n}\n" % (etype, key, body)

# build, sorted by key for determinism
rows = []
missing = []
for doi, key in km.items():
    r = by_doi.get((doi or "").lower())
    if not r:
        missing.append((key, doi))
        continue
    rows.append((key, r))
rows.sort(key=lambda kr: kr[0].lower())

header = ("% Bibliography for \"The Ethical Debt\" — generated by scripts/build_bibliography.py\n"
          "% One entry per citation key; source: CrossRef metadata (provenance/crossref_metadata.json).\n\n")
with open("content/references.bib", "w", encoding="utf-8") as fh:
    fh.write(header)
    for key, r in rows:
        fh.write(entry(key, r))
        fh.write("\n")

print("references.bib entries written:", len(rows))
print("keys with NO metadata (skipped):", len(missing))
for k, d in missing[:20]:
    print("   MISSING:", k, d)
# uniqueness of keys
keys = [k for k, _ in rows]
print("duplicate keys:", len(keys) - len(set(keys)))
